# Generates hw5-stats.md. Run from the repository root:
#     uv run python -m analysis.report.hw5_stats
"""HW5 dataset statistics: labels, the 20/40/40 split, and the judge input.

Every number is recomputed from the saved state files, and each check that
backs a claim in the write-up (one label per conversation, Pass = 1, disjoint
splits, label-free judge input) raises if it no longer holds. Offline only.
"""
import json
import re
from collections import Counter
from pathlib import Path

from analysis.run_judges import _load_transcripts

MODE = "narrates_or_overexplains"
JUDGE = f"{MODE}-v6"
OUT = Path("analysis/report/hw5-stats.md")



def load(path):
    return json.loads(Path(path).read_text())


LABELS = [json.loads(line) for line in Path(f"analysis/state/hw5_labels/{MODE}.jsonl").read_text().splitlines()]
SPLITS = load("analysis/state/splits.json")[MODE]
INPUTS = load("analysis/state/hw5_trace_inputs.json")
JUDGE_REC = load(f"analysis/state/judges/{JUDGE}.json")
TEST = load(f"analysis/report/test-{JUDGE}.json")
PREV = load(f"analysis/report/prevalence-{JUDGE}.json")

LAB = {r["trace_id"]: r["label"] for r in LABELS}
NAMES = ("train", "dev", "test")
# What a judge input may contain: the transcript and nothing else.
INPUT_KEYS = {"trace_id", "trace"}
ROLES = {"earlier_user", "earlier_assistant_reply", "user", "tool_call", "tool_result", "final_reply"}
MESSAGE_KEYS = {"role", "text", "arguments", "content"}


def norm(text):
    return re.sub(r"\s+", " ", text.lower()).strip()


def counts(ids):
    c = Counter(LAB[t] for t in ids)
    return c[1], c[0]


def pct(a, b):
    return f"{100 * a / b:.1f}%"


def check_labels():
    assert {r["label"] for r in LABELS} <= {0, 1}, "labels must be 0/1"
    assert len(LAB) == len(LABELS), "duplicate trace ids in the label file"
    transcripts = _load_transcripts()
    sessions = Counter(transcripts[t]["session_id"] for t in LAB)
    assert max(sessions.values()) == 1, "a conversation has more than one label"
    return len(sessions)


def check_splits():
    sets = {k: set(SPLITS[k]) for k in NAMES}
    for i, a in enumerate(NAMES):
        for b in NAMES[i + 1:]:
            assert not sets[a] & sets[b], f"{a} and {b} overlap"
    assert set().union(*sets.values()) == set(LAB), "splits do not cover exactly the labeled traces"


def check_inputs():
    assert {r["trace_id"] for r in INPUTS} == set(LAB), "judge inputs do not match the labels"
    for r in INPUTS:
        assert set(r) == INPUT_KEYS, f"{r['trace_id']} has extra fields {set(r) - INPUT_KEYS}"
        for m in r["trace"]:
            assert m["role"] in ROLES, f"{r['trace_id']} has role {m['role']}"
            assert set(m) <= MESSAGE_KEYS, f"{r['trace_id']} message has fields {set(m) - MESSAGE_KEYS}"
        assert sum(m["role"] == "final_reply" for m in r["trace"]) == 1, f"{r['trace_id']} needs one final reply"
    return Counter(m["role"] for r in INPUTS for m in r["trace"])


def prompt_overlap():
    """Final replies from each split that appear verbatim in the frozen prompt."""
    prompt = norm(JUDGE_REC["prompt_text"])
    reply = {r["trace_id"]: norm(next(m["text"] for m in r["trace"] if m["role"] == "final_reply"))
             for r in INPUTS}
    # A 60-character prefix catches an example quoted in full or lightly trimmed.
    return {k: sum(len(reply[t]) >= 24 and reply[t][:60] in prompt for t in SPLITS[k]) for k in NAMES}


def main():
    n_sessions = check_labels()
    check_splits()
    roles = check_inputs()
    overlap = prompt_overlap()
    assert overlap["dev"] == overlap["test"] == 0, f"dev/test replies appear in the {JUDGE} prompt: {overlap}"

    n = len(LABELS)
    n_pass, n_fail = counts(LAB)
    review = Counter(r["review"] for r in LABELS)
    review_fail = Counter(r["review"] for r in LABELS if r["label"] == 0)
    fractions = SPLITS["fractions"]
    turns = [sum(m["role"] == "user" or m["role"] == "earlier_user" for m in r["trace"]) for r in INPUTS]

    lines = [
        "# HW5 statistics: `narrates_or_overexplains`",
        "",
        "Generated by `analysis/report/hw5_stats.py` from the saved state files. Offline; no model calls.",
        "",
        "## Labels",
        "",
        f"- **{n}** labeled conversations, one label per conversation ({n_sessions} distinct sessions).",
        "- Convention: **Pass = 1**, Fail = 0.",
        f"- **{n_pass} Pass** ({pct(n_pass, n)}), **{n_fail} Fail** ({pct(n_fail, n)}).",
        "",
        "| Who set the label | Labels | Fail |",
        "|---|---:|---:|",
    ]
    for k in ("set_by_reviewer", "confirmed_by_reviewer", "claude_unreviewed"):
        lines.append(f"| `{k}` | {review[k]} | {review_fail[k]} |")
    lines += [
        f"| **Total** | **{n}** | **{n_fail}** |",
        "",
        "## Split",
        "",
        (f"Fractions {' / '.join(f'{f:.0%}' for f in fractions)} with seed {SPLITS['seed']} "
         f"(created {SPLITS['created_at'][:10]}). The splits are disjoint and cover all {n} labels."),
        "",
        "| Split | Use | n | Pass | Fail | Fail share |",
        "|---|---|---:|---:|---:|---:|",
    ]
    use = {"train": "few-shot examples", "dev": "prompt iteration", "test": "held out; scored once"}
    for k in NAMES:
        p, f = counts(SPLITS[k])
        lines.append(f"| {k} | {use[k]} | {p + f} | {p} | {f} | {pct(f, p + f)} |")
    lines += [
        f"| **Total** | | **{n}** | **{n_pass}** | **{n_fail}** | **{pct(n_fail, n)}** |",
        "",
        f"The 40/40 fractions of {n} round to {len(SPLITS['dev'])} dev and {len(SPLITS['test'])} test.",
        "",
        "## Judge input",
        "",
        ("Each input is `{trace_id, trace}` and holds only the conversation. It has no labels, "
         "reviewer notes, or scenario metadata; the script fails if any other field appears."),
        "",
        "| Message role | Count |",
        "|---|---:|",
    ]
    for role in ("earlier_user", "earlier_assistant_reply", "user", "tool_call", "tool_result", "final_reply"):
        lines.append(f"| `{role}` | {roles[role]} |")
    multi = sum(t > 1 for t in turns)
    lines += [
        "",
        (f"- User turns per input: median {sorted(turns)[len(turns) // 2]}, max {max(turns)}; "
         f"{multi} of {n} inputs include earlier turns."),
        (f"- Final replies quoted in the frozen `{JUDGE}` prompt: "
         f"train {overlap['train']}, dev {overlap['dev']}, test {overlap['test']}."),
        "",
        f"## Frozen judge (`{JUDGE}`, {TEST['model']}) on test",
        "",
        (f"Frozen {TEST['frozen_at'][:10]} and scored once on the {TEST['n']} test conversations. "
         "Per-run dev metrics are in [figures/hw5-judge-comparison.md](figures/hw5-judge-comparison.md)."),
        "",
        "| Metric | Value | 95% interval |",
        "|---|---:|---|",
        (f"| TPR (Pass recall) | {TEST['tpr']:.3f} ({TEST['tp']}/{TEST['tp'] + TEST['fn']}) "
         f"| {TEST['tpr_interval'][0]:.3f}–{TEST['tpr_interval'][1]:.3f} |"),
        (f"| TNR (Fail recall) | {TEST['tnr']:.3f} ({TEST['tn']}/{TEST['tn'] + TEST['fp']}) "
         f"| {TEST['tnr_interval'][0]:.3f}–{TEST['tnr_interval'][1]:.3f} |"),
        f"| Agreement | {TEST['agreement']:.3f} ({TEST['tp'] + TEST['tn']}/{TEST['n']}) | |",
        "",
        f"Confusion (Pass positive): TP {TEST['tp']}, FN {TEST['fn']}, TN {TEST['tn']}, FP {TEST['fp']}.",
        "",
        "## Failure prevalence on unlabeled traces",
        "",
        "| Traces | n | Raw Fail rate | Corrected Fail prevalence | 95% CI |",
        "|---|---:|---:|---:|---|",
    ]
    for k, v in PREV.items():
        lines.append(f"| {k} | {v['n_unlabeled']} | {v['raw']:.3f} | {v['corrected']:.3f} "
                     f"| {v['ci_low']:.3f}–{v['ci_high']:.3f} |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
